# Generated by Django 5.2.6 on 2026-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_user_created_by_user_updated_at_user_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
