# Generated by Django 5.2.6 on 2026-02-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_user_designation_user_name_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ORG_ADMIN", "Organization Admin"),
                    ("OFFICE_ADMIN", "Office Admin"),
                    ("OFFICE_MANAGER", "Office Manager"),
                    ("SUPERVISOR", "Supervisor"),
                ],
                default="OFFICE_MANAGER",
                max_length=20,
            ),
        ),
    ]
