# Generated by Django 5.2.6 on 2026-02-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="emp_code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
