# Generated by Django 5.2.6 on 2026-03-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organization", "0007_office_managers_m2m"),
        ("Users", "0005_user_emp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="Organization.office",
            ),
        ),
    ]
