# Generated by Django 5.2.6 on 2026-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organization", "0003_office_created_by_office_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="full_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="office",
            name="num_biometric_devices",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
