# Generated by Django 5.2.6 on 2026-02-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organization", "0004_office_full_address_office_num_biometric_devices"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="organization",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
