# Generated by Django 5.2.6 on 2026-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Organization", "0005_organization_address_organization_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="pincode",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
