# Generated by Django 5.2.6 on 2026-02-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Employee", "0001_initial"),
        ("Organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="Organization.office",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="Organization.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("organization", "emp_code"), name="employee_org_emp_code_unique"
            ),
        ),
    ]
