# Generated by Django 5.2.6 on 2026-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0003_employee_created_by_employee_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
