# Generated by Django 5.2.6 on 2026-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0004_employee_email_employee_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_profiles/"
            ),
        ),
    ]
