# Generated by Django 5.2.6 on 2026-02-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0005_employee_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORG_ADMIN", "Org Admin"),
                    ("OFFICE_ADMIN", "Office Admin"),
                    ("MANAGER", "Manager"),
                    ("EMPLOYEE", "Staff"),
                    ("SUPPORT_STAFF", "Support Staff"),
                ],
                max_length=32,
            ),
        ),
    ]
