# Generated by Django 5.2.6 on 2026-02-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0006_employee_date_of_birth_employee_gender_and_more"),
        ("Shifts", "0002_employeeshift_created_at_employeeshift_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="Shifts.shift",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORG_ADMIN", "Org Admin"),
                    ("OFFICE_ADMIN", "Office Admin"),
                    ("MANAGER", "Manager"),
                    ("SUPERVISOR", "Supervisor"),
                    ("EMPLOYEE", "Staff"),
                    ("SUPPORT_STAFF", "Support Staff"),
                ],
                max_length=32,
            ),
        ),
    ]
