# Generated by Django 5.2.6 on 2026-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0007_employee_shift_alter_employee_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="government_id_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="employee",
            name="government_id_value",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
