# Generated by Django 5.2.6 on 2026-02-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0008_employee_government_id_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="government_id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("License", "License"),
                    ("PanCard", "Pan Card"),
                    ("AadhaarCard", "Aadhaar Card"),
                    ("VoterID", "Voter ID"),
                ],
                max_length=32,
            ),
        ),
    ]
