# Generated by Django 5.2.6 on 2026-02-24 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0009_alter_employee_government_id_type"),
        ("Organization", "0007_office_managers_m2m"),
        ("Shifts", "0003_delete_employeeshift"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["office_id", "is_active"], name="emp_office_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["office_id", "is_active", "phone_number"],
                name="emp_office_active_phone_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["office_id", "is_active", "email"],
                name="emp_office_active_email_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["office_id", "is_active", "government_id_value"],
                name="emp_office_active_govt_id_idx",
            ),
        ),
    ]
