# Generated by Django 5.2.6 on 2026-02-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Employee", "0001_initial"),
        ("Organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("grace_minutes", models.PositiveSmallIntegerField(default=0)),
                ("is_night_shift", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="Organization.office",
                    ),
                ),
            ],
            options={
                "db_table": "shift",
                "ordering": ["office", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="Employee.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_assignments",
                        to="Shifts.shift",
                    ),
                ),
            ],
            options={
                "db_table": "employee_shift",
                "ordering": ["employee", "-effective_from"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "effective_from"),
                        name="employee_shift_effective_from_unique",
                    )
                ],
            },
        ),
    ]
