# Generated by Django 5.2.6 on 2026-02-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Shifts", "0002_employeeshift_created_at_employeeshift_created_by_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeShift",
        ),
    ]
