# Generated by Django 5.2.6 on 2026-02-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BiometricLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_code", models.CharField(db_index=True, max_length=64)),
                ("punch_time", models.DateTimeField(db_index=True)),
                ("device_id", models.CharField(blank=True, max_length=128)),
                ("raw_payload", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Biometric log",
                "verbose_name_plural": "Biometric logs",
                "db_table": "biometric_log",
                "ordering": ["punch_time", "id"],
            },
        ),
    ]
