# Generated by Django 5.2.6 on 2026-02-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Biometric", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsslSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=128, unique=True)),
                ("last_device_log_id", models.BigIntegerField(default=0)),
                ("last_sync_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ESSL sync state",
                "verbose_name_plural": "ESSL sync states",
                "db_table": "essl_sync_state",
            },
        ),
    ]
