# Generated by Django 5.2.6 on 2026-02-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Biometric", "0002_esslsyncstate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EsslSyncState",
        ),
    ]
