# Generated by Django 5.2.6 on 2026-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Biometric", "0003_delete_esslsyncstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyEsslBiometricAttendanceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DeviceLogId", models.BigIntegerField(db_index=True, unique=True)),
                ("DownloadDate", models.DateTimeField(blank=True, null=True)),
                ("DeviceId", models.CharField(blank=True, max_length=128)),
                ("UserId", models.CharField(blank=True, db_index=True, max_length=64)),
                ("LogDate", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("Direction", models.CharField(blank=True, max_length=32)),
                ("AttDirection", models.CharField(blank=True, max_length=32)),
                ("C1", models.CharField(blank=True, max_length=64)),
                ("C2", models.CharField(blank=True, max_length=64)),
                ("C3", models.CharField(blank=True, max_length=64)),
                ("C4", models.CharField(blank=True, max_length=64)),
                ("C5", models.CharField(blank=True, max_length=64)),
                ("C6", models.CharField(blank=True, max_length=64)),
                ("C7", models.CharField(blank=True, max_length=64)),
                ("WorkCode", models.CharField(blank=True, max_length=64)),
                ("hrapp_syncstatus", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "verbose_name": "Dummy biometric attendance data",
                "verbose_name_plural": "Dummy biometric attendance data",
                "db_table": "DummyEsslBiometricAttendanceData",
                "ordering": ["-LogDate", "DeviceLogId"],
            },
        ),
    ]
