# Generated by Django 5.2.6 on 2026-03-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Biometric", "0004_dummyesslbiometricattendancedata"),
        ("Organization", "0007_office_managers_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_devices",
                        to="Organization.office",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric device",
                "verbose_name_plural": "Biometric devices",
                "db_table": "biometric_device",
                "ordering": ["office", "device_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("office", "device_id"),
                        name="biometric_device_office_device_id_unique",
                    )
                ],
            },
        ),
    ]
