# Generated by Django 5.2.6 on 2026-02-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("first_in", models.DateTimeField(blank=True, null=True)),
                ("last_out", models.DateTimeField(blank=True, null=True)),
                (
                    "working_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("late_minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Present"),
                            ("A", "Absent"),
                            ("L", "Late"),
                            ("WO", "Weekly Off"),
                        ],
                        default="A",
                        max_length=4,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "attendances",
                "db_table": "attendance",
                "ordering": ["-date", "employee"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_datetime", models.DateTimeField()),
                ("to_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "attendance_run",
                "ordering": ["-created_at"],
            },
        ),
    ]
