# Generated by Django 5.2.6 on 2026-02-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Attendance", "0001_initial"),
        ("Employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="Employee.employee",
            ),
        ),
    ]
