# Generated by Django 5.2.6 on 2026-02-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Attendance", "0002_initial"),
        ("Organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerun",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_runs",
                to="Organization.office",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("employee", "date"), name="attendance_employee_date_unique"
            ),
        ),
    ]
